language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t avinashnallam4441/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true avinashnallam4441/react-test npm test

after_success:
  - docker build -t avinashnallam4441/multi-client ./client
  - docker build -t avinashnallam4441/multi-nginx ./nginx
  - docker build -t avinashnallam4441/multi-server ./server
  - docker build -t avinashnallam4441/multi-worker ./worker
  # Log into the docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # tag the images first
  - $ docker tag multi-client avinashnallam4441/multi-client
  - $ docker tag multi-nginx avinashnallam4441/multi-nginx
  - $ docker tag multi-server avinashnallam4441/multi-server
  - $ docker tag multi-worker avinashnallam4441/multi-worker
  # Take those images and push to docker-hub
  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker
